version: '3.8'
services:
  ingress:
    build:
      context: ../ingress
      dockerfile: Dockerfile
    image: aar0npham/dha-pr-ingress:latest
    restart: always
  pr-nocuda:
    build:
      context: ../price_recommender
      dockerfile: Dockerfile
    image: aar0npham/dha-pr:with-nocuda
