version: "3.8"
services:
  ingress:
    build:
      context: ../ingress
      dockerfile: build/ingress.dockerfile
    image: aar0npham/dha-pr-ingress:latest
    restart: always
  swaggerui:
    build:
      context: ../ingress
      dockerfile: build/swagger.dockerfile
    image: aar0npham/dha-pr-swagger:latest
  pr-nocuda:
    build:
      context: ../price_recommender
      dockerfile: build/with-nocuda.dockerfile
    image: aar0npham/dha-pr:with-nocuda
